### ISSUE TITLE
Prerequisites for Debian Stretch

### ISSUE THREAD

**Issue by KipourosV** [K4YT3X/wireguard-mesh-configurator#2]
Was getting errors when pip installing the requirements.

**libncurses5-dev** is needed on Debian Stretch.

(Oh and thank you very much for the fast response to my previous request, and this tool)

**Comment by K4YT3X** [comment]
> Was getting errors when pip installing the requirements.
> python3-dev & libncurses5-dev are needed on Debian Stretch.

Can you be more specific on the issue? How did you figure out that the two packages are required on Debian?


> (Oh and thank you very much for the fast response to my previous request, and this tool)

You're welcome. Glad if it helped.

**Comment by KipourosV** [comment]
I will try to recreate in a vm real quick and come back with specifics...

**Comment by K4YT3X** [comment]
I see, so it's readline that requires libncurses dev library. I'll write that into the prerequisites.
On my Kali there's a package called `libncurses-dev` for it. Does one exist on Debian?

**Comment by KipourosV** [comment]
Yes, for debian it's **libncurses5-dev** as I mention in the first post.

After installing that the requirements installation goes through without a hitch.

**Comment by K4YT3X** [comment]
oh I was just wondering if there's a package called `libncurses-dev` without a version number that points to the newest version of libncurses. I just checked that on my Debian machine, and there doesn't seem to be one. I'll list libncurses5-dev into the prerequisites.

**Comment by K4YT3X** [comment]
I have already pushed the new documentation. Please open new issues if you find more of it.

**Comment by Dinkum** [comment]
I am running an Ubuntu 18.04.1 x64 DigitalOcean VPS and got the same thing. Your solution works (you actually updated the documentation as I was installing) but I thought you might want to know this is not restricted to just pure Debian.

**Comment by K4YT3X** [comment]
> I thought you might want to know this is not restricted to just pure Debian

I understand that, which is why I stated that it's whichever library that contains ncurses dev files, the package name on debian is just an example.
