### ISSUE TITLE
Description Field

### ISSUE THREAD

**Issue by pejesat** [k4yt3x/wireguard-mesh-configurator#4]
Thank you for your script.
It would be great if you add an descpription field to peers, that would be very helpful (to fill in common name).
cu Peje

**Comment by k4yt3x** [comment]
Hi @pejesat , That's not a bad idea. Maybe I should add a description during the execution of the script like:

```console
Public Address (leave empty if client only) [IP/FQDN]:
```

Do you think this would be better of if I write a description section for it in the documentation?

**Comment by pejesat** [comment]
Hi I think it would be nice during execution, and later maybe editable (e).
thank you

**Comment by k4yt3x** [comment]
@pejesat I pushed an update this afternoon (UTC-4). See if it works the way you want it to, or if I should make it more detailed.

**Comment by pejesat** [comment]
Hi its better, but what I meant is something like in openwrt luci wireguard, an additonal field for descprition, have a look at the picture.
Thanks cu Peje
Am Montag, Mai 06, 2019 05:39 CEST, K4YT3X <notifications@github.com> schrieb:
 
@pejesat I pushed an update this afternoon (UTC-4). See if it works the way you want it to, or if I should make it more detailed.

**Comment by pejesat** [comment]
Hi sorry what I would like would be an additional information resulting in:
[Interface]
PrivateKey = xxxxxxxxxxxxxxxxx=
Address = 1.1.1.1
[Peer]
**#This is Peer k4y3x**
PublicKey
..
cu Peje

**Comment by k4yt3x** [comment]
Ah okay I see, like a comment/description for the peer right?
I'll work on that shortly.

**Comment by k4yt3x** [comment]
Check out the newest version.

**Comment by pejesat** [comment]
Thank you very much, this is perfect!!!
cu Peje
Am Donnerstag, Mai 16, 2019 20:31 CEST, K4YT3X <notifications@github.com> schrieb:
 
Check out the newest version.
